logging:
  config: classpath:logback/logback-dev.xml
  level:
    nil:
      ed:
        chatroom:
          mapper: info


spring:
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /chatroom/**
  redis:
    host: localhost
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/livechat?useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT-8&allowPublicKeyRetrieval=true
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/chatroom?useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT-8&allowPublicKeyRetrieval=true

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true

kafka:
  servers: localhost:9092

server:
  port: 12011
  servlet:
    session:
      cookie:
        http-only: false # 默认为true，设置为false前端才可以获取到cookie